/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/7TZF2ETooRE
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'
import { Arimo } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
// import { Button } from "../ui/button"

export function MainPage() {
  return (
    (<div className="flex flex-col min-h-screen">
      <header
        className="bg-primary text-primary-foreground py-2 px-4 md:px-6 flex items-center justify-center">
        <nav className="flex items-center gap-4">
          <Link
            href="#"
            className="inline-flex items-center justify-center rounded-md px-4 py-2 text-sm font-medium transition-colors hover:bg-primary/80 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
            prefetch={false}>
            Problem Set
          </Link>
          <Link
            href="#"
            className="inline-flex items-center justify-center rounded-md px-4 py-2 text-sm font-medium transition-colors hover:bg-primary/80 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
            prefetch={false}>
            Contests
          </Link>
          <Link
            href="#"
            className="inline-flex items-center justify-center rounded-md px-4 py-2 text-sm font-medium transition-colors hover:bg-primary/80 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
            prefetch={false}>
            Leaderboard
          </Link>
        </nav>
      </header>
      <main className="flex-1 py-8 px-4 md:px-6">
        <div className="container max-w-4xl mx-auto">
          <h1 className="text-3xl font-bold mb-6">Problem Set</h1>
          <ul className="space-y-4">
            <li className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-semibold">Two Sum</h2>
                <p className="text-muted-foreground text-sm">
                  Given an array of integers nums and an integer target, return indices of the two numbers such that
                  they add up to target.
                </p>
              </div>
              {/* <Button className="w-auto">Solve</Button> */}
            </li>
            <li className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-semibold">Reverse Integer</h2>
                <p className="text-muted-foreground text-sm">
                  Given a 32-bit signed integer, reverse digits of the integer.
                </p>
              </div>
              {/* <Button className="w-auto">Solve</Button> */}
            </li>
            <li className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-semibold">Longest Palindromic Substring</h2>
                <p className="text-muted-foreground text-sm">
                  Given a string s, return the longest palindromic substring in s.
                </p>
              </div>
              {/* <Button className="w-auto">Solve</Button> */}
            </li>
            <li className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-semibold">Merge Two Sorted Lists</h2>
                <p className="text-muted-foreground text-sm">
                  Merge two sorted linked lists and return it as a sorted list.
                </p>
              </div>
              {/* <Button className="w-auto">Solve</Button> */}
            </li>
            <li className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-semibold">Longest Substring Without Repeating Characters</h2>
                <p className="text-muted-foreground text-sm">
                  Given a string s, find the length of the longest substring without repeating characters.
                </p>
              </div>
              {/* <Button className="w-auto">Solve</Button> */}
            </li>
            <li className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-semibold">Median of Two Sorted Arrays</h2>
                <p className="text-muted-foreground text-sm">
                  Given two sorted arrays nums1 and nums2, find the median of the two sorted arrays.
                </p>
              </div>
              {/* <Button className="w-auto">Solve</Button> */}
            </li>
            <li className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-semibold">Reverse Linked List</h2>
                <p className="text-muted-foreground text-sm">
                  Given the head of a singly linked list, reverse the list.
                </p>
              </div>
              {/* <Button className="w-auto">Solve</Button> */}
            </li>
            <li className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-semibold">Valid Parentheses</h2>
                <p className="text-muted-foreground text-sm">
                  Given a string s containing just the characters '(', ')', ', ', '[' and ']', determine if the input
                  string is valid.
                </p>
              </div>
              {/* <Button className="w-auto">Solve</Button> */}
            </li>
          </ul>
        </div>
      </main>
      <footer className="bg-muted text-muted-foreground py-4 px-4 md:px-6">
        <div className="container max-w-4xl mx-auto text-center text-sm">
          &copy; 2024 Competitive Programming. All rights reserved.
        </div>
      </footer>
    </div>)
  );
}
